server:
  port: 8083

spring:
 application:
  name: inghubs-case
 datasource:
  url: jdbc:h2:mem:inghubs-db;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=3000
  driverClassName: org.h2.Driver
  username: sa
  password:
 cache:
  type: caffeine
 caffeine:
  spec: maximumSize=500,expireAfterWrite=10m
  
 jpa:
  defer-datasource-initialization: true
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
  hibernate:
   ddl-auto: create

 sql:
  init:
   mode: always
  
 h2:
  console:
   enabled: true
  
 messages:
  basename: i18n
  encoding: UTF-8
 
jwt:
  secret: "2bNokLO7U3XYOKC3FjQh3o4hH5l7kY2l1KxYx3sXq4w="
  expiration: 3600000

springdoc:
  api-docs:
    path: /api-docs
